name=OzkLed
version=1.0.0
author=Hamza Ozlam
maintainer=Hamza Özkan <info@hamzaozkan.com.tr>
sentence=Arduino library for ESP32
paragraph=Esp32 bluetooth için üretilmiş led kontrol yazılımı 
category=Communication
url=https://github.com/hmz06967/ozkled
architectures=*
depends=
