name=OzkLed
version=1.0.3
author=Hamza Ozkan
maintainer=Hamza Özkan <info@hamzaozkan.com.tr>
sentence=Arduino library for ESP32
paragraph=Esp32 ile ws2812 neopixeli android uygulaması ile kontrol eden gömülü arayüz yazılımı
category=Communication
url=https://github.com/hmz06967/ozkled
architectures=*
depends=
